[package]
name = "d1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "a"
path = "./src/main.rs"

[[bin]]
name = "b"
path = "./src/main_2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
