[package]
name = "d3"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "part1"

[[bin]]
path = "src/main_2.rs"
name = "part2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "*"